### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by swarley** [shardlab/discordrb#49]
Buttons are hitting the API soon, and will offer new methods of interacting with messages.

We will need to support the initial components; ActionRow and Button (Potentially the dropdown menu as well depending on how quickly I get this done 😅 ).

Each will require a data class for receiving interactions, and a builder for sending them with messages.

Ideally we will also have some form of resuable "component collection", but this is still up in the air and an initial implementation can be shipped without it.

**Comment by MHatfull** [comment]
I see this has been moved to Done, could you link to the relevant documentation please?

**Comment by swarley** [comment]
https://drb.shardlab.dev/main/Discordrb/EventContainer.html#button-instance_method
https://drb.shardlab.dev/main/Discordrb/Events/ButtonEvent.html
And message sending methods have access to a yielded `View`, documentation for which can be found here https://drb.shardlab.dev/main/Discordrb/Webhooks/View.html
and examples here https://github.com/shardlab/discordrb/blob/main/examples/slash_commands.rb#L72-L86
https://github.com/shardlab/discordrb/blob/main/examples/slash_commands.rb#L97-L106

**Comment by MHatfull** [comment]
it looks like this code isn't in the gem on rubygems, what's the best way to install the gem with this functionality? Should I install directly from the github main branch or is that not considered stable?

**Comment by Daniel-Worrall** [comment]
If you want to run the latest code, we recommend using bundler with the following line in the Gemfile:
`gem 'discordrb', github: 'shardlab/discordrb', branch: 'main'`

Since the gem is so outdated, we recommend this until we have a release ready to go. There are bugs you can encounter with the latest gem since there have been updates on discords side but have been fixed on main.

Also be sure to check out the discord for the most up to date information and discussions
