### ISSUE TITLE
Implement ApplicationCommandContainer

### ISSUE THREAD

**Issue by TrevorHinesley** [shardlab/discordrb#79]
Much like CommandContainer and EventContainer, it seems there'd be benefit to adding an ApplicationCommandContainer or something similar, to modularize adding slash commands.

**Comment by swarley** [comment]
Not sure how I feel about this. CommandContainer exists because "commands" are an artificial event created by the library. Application commands on the other hand come directly from the API like other events in the container. There's not really a benefit to moving them into their own container other than separating some of the logic away from more straight forward events. An argument could also be made that slash commands internally should use the name as a filtering method and be treated like all other events.

Would like to get input from other contributors on this.

**Comment by TrevorHinesley** [comment]
That makes sense for sure. I was really just suggesting a way to be able to build slash commands in a modular fashion, similar to how events and regular commands can currently be built as separate modules and extended as needed.

**Comment by swarley** [comment]
The desired features can be achieved through existing usage of `EventContainer`, just include and define your handlers. Closing this for now but will reopen with sufficient cause.
